WebPushDemo/Models/Devices.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebPushDemo.Models
{
    public class Devices
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PushEndpoint { get; set; }
        public string PushP256DH { get; set; }
        public string PushAuth { get; set; }
    }
}

WebPushDemo/Models/ErrorViewModel.cs
using System;

namespace WebPushDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebPushDemo/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using WebPush;
using WebPushDemo.Models;

namespace WebPushDemo.Controllers
{
    public class DevicesController : Controller
    {
        private readonly WebPushDemoContext _context;

        private readonly IConfiguration _configuration;

        public DevicesController(WebPushDemoContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        // GET: Devices
        public async Task<IActionResult> Index()
        {
            return View(await _context.Devices.ToListAsync());
        }

        // GET: Devices/Create
        public IActionResult Create()
        {
            ViewBag.PublicKey = _configuration.GetSection("VapidKeys")["PublicKey"];

            return View();
        }

        // POST: Devices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,PushEndpoint,PushP256DH,PushAuth")] Devices devices)
        {
            if (ModelState.IsValid)
            {
                _context.Add(devices);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(devices);
        }
       
        // GET: Devices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var devices = await _context.Devices
                .SingleOrDefaultAsync(m => m.Id == id);
            if (devices == null)
            {
                return NotFound();
            }

            return View(devices);
        }

        // POST: Devices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var devices = await _context.Devices.SingleOrDefaultAsync(m => m.Id == id);
            _context.Devices.Remove(devices);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

WebPushDemo/Controllers/WebPushController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using WebPush;
using WebPushDemo.Models;

namespace WebPushDemo.Controllers
{
    public class WebPushController : Controller
    {
        private readonly IConfiguration _configuration;

        private readonly WebPushDemoContext _context;

        public WebPushController(WebPushDemoContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        public IActionResult Send(int? id)
        {
            return View();
        }

        [HttpPost, ActionName("Send")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Send(int id)
        {
            var payload = Request.Form["payload"];
            var device = await _context.Devices.SingleOrDefaultAsync(m => m.Id == id);

            string vapidPublicKey = _configuration.GetSection("VapidKeys")["PublicKey"];
            string vapidPrivateKey = _configuration.GetSection("VapidKeys")["PrivateKey"];

            var pushSubscription = new PushSubscription(device.PushEndpoint, device.PushP256DH, device.PushAuth);
            var vapidDetails = new VapidDetails("mailto:example@example.com", vapidPublicKey, vapidPrivateKey);

            var webPushClient = new WebPushClient();
            await webPushClient.SendNotificationAsync(pushSubscription, payload, vapidDetails);

            return View();
        }

        public IActionResult GenerateKeys()
        {
            var keys = VapidHelper.GenerateVapidKeys();
            ViewBag.PublicKey = keys.PublicKey;
            ViewBag.PrivateKey = keys.PrivateKey;
            return View();
        }
    }
}

WebPushDemo/Views/Devices/Create.cshtml
@model WebPushDemo.Models.Devices
@section Scripts
{
    <script src="@Url.Content("~/js/CreateDevice.js")"></script>
}

@{
    ViewData["Title"] = "Create";
}

<h2>Add Device</h2>
<hr />
<div class="row">
    <div class="alert alert-info">
        <strong>Developer Notes:</strong>
        <ul>
            <li>You can find the logic for registering a device in wwwroot/js/CreateDevice.js</li>
            <li>ServiceWorkers on chrome will only work on sites with ssl enabled or local webservers.</li>
            <li>Microsoft Edge requires enabling service workers.</li>
        </ul>
    </div>
    <div class="alert alert-danger" style="display: none;">
        <strong>Error:</strong>
        <ul id="errorMessage"></ul>
    </div>

    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="width:500px">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" required />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="well" style="width: 500px;">
                <h4>Web Push Details</h4>
                <span style="font-size: 12px;">These values will automatically become populated once correct permissions are given by the browser.</span>
                <hr/>
                <div class="form-group">
                    <label asp-for="PushEndpoint" class="control-label"></label>
                    <input asp-for="PushEndpoint" class="form-control" readonly required/>
                    <span asp-validation-for="PushEndpoint" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PushP256DH" class="control-label"></label>
                    <input asp-for="PushP256DH" class="form-control" readonly required/>
                    <span asp-validation-for="PushP256DH" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PushAuth" class="control-label"></label>
                    <input asp-for="PushAuth" class="form-control" readonly required/>
                    <span asp-validation-for="PushAuth" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>
    //Vapid public key.
    var applicationServerPublicKey = '@ViewBag.PublicKey';
</script>

WebPushDemo/Views/Devices/Delete.cshtml
@model WebPushDemo.Models.Devices

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this device?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PushEndpoint)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PushEndpoint)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PushP256DH)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PushP256DH)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PushAuth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PushAuth)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-default">Back to List</a>
    </form>
</div>

WebPushDemo/Views/Devices/Index.cshtml
@model IEnumerable<WebPushDemo.Models.Devices>

@{
    ViewData["Title"] = "Registered Devices";
}

<div class="col-sm-6">
    <h2>Registered Devices</h2>
</div>
<div class="col-sm-6">
    <div class="pull-right" style="margin-top: 15px;">
        <a asp-action="Create" class="btn btn-primary">Add Device</a>
    </div>
</div>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PushEndpoint)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PushP256DH)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.PushAuth)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td style="max-width: 100px; white-space: nowrap; text-overflow: ellipsis; overflow: hidden;">
                    @Html.DisplayFor(modelItem => item.PushEndpoint)
                </td>
                <td style="max-width: 100px; white-space: nowrap; text-overflow: ellipsis; overflow: hidden;">
                    @Html.DisplayFor(modelItem => item.PushP256DH)
                </td>
                <td style="max-width: 100px; white-space: nowrap; text-overflow: ellipsis; overflow: hidden;">
                    @Html.DisplayFor(modelItem => item.PushAuth)
                </td>
                <td>
                    <a asp-controller="WebPush" asp-action="Send" asp-route-id="@item.Id">Send</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="5" style="text-align: center; font-weight: bold;">
                    No devices registered yet.
                </td>
            </tr>
        }
    </tbody>
</table>

WebPushDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebPushDemo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Devices" asp-action="Index" class="navbar-brand">WebPushDemo</a>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WebPushDemo</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebPushDemo/Views/WebPush/GenerateKeys.cshtml
@model WebPushDemo.Models.Devices
@{
    ViewData["Title"] = "Configure Keys";
}

<h2>Configure Keys</h2>
<div class="alert alert-warning alert-dismissable">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Developer Notes:</strong>
    <ul>
        <li>Web Push notification require a public and private key to send a payload.</li>
        <li>Newly generated keys for you to use are below.</li>
        <li>Key generation code can be viewed in Controllers/WebPushController.cs:GenerateKeys</li>
    </ul>
</div>

<p>Add the following keys to appsettings.json</p>
<pre>
  "VapidKeys" : {
    "PublicKey": "@ViewBag.PublicKey",
    "PrivateKey":  "@ViewBag.PrivateKey" 
  } 
</pre>

WebPushDemo/Views/WebPush/Send.cshtml
@model WebPushDemo.Models.Devices

@section Scripts
{
    <script src="@Url.Content("~/js/SendDevice.js")"></script>
}
@{
    ViewData["Title"] = "Send";
}
<h2>Send Push Message</h2>
<hr />

<div class="row">
    <div class="alert alert-info">
        <strong>Developer Notes:</strong>
        <ul>
            <li>You can find the logic for sending a web push notification in Controllers/WebPushController.cs:Send</li>
            <li>The Payload Generation Helper fields below are not sent to the web push api. They are simply used to generate the json payload which will be sent.</li>
            <li>Client side code for handling push notifications can be found at wwwroot/sw.js</li>
            <li>You can include any data in your payload, as long as your sw.js handles it.</li>
        </ul>
    </div>
    <div class="col-md-4">
        <div class="well" style="width: 500px;">
            <h4>Payload Generation Helper</h4>
            <span style="font-size: 12px;">Type your Title and Message and your payload will be generated below.</span>
            <hr/>
            <div class="form-group">
                <label class="control-label" for="Title">Title</label>
                <input class="form-control" type="text" id="Title" name="Title" value="">
            </div>
            <div class="form-group">
                <label class="control-label" for="Message">Message</label>
                <input class="form-control" type="text" id="Message" name="Message" value="">
            </div>
        </div>
        
        <form asp-action="Send">
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label class="control-label" for="Payload">Payload</label>

                <textarea id="Payload" name="Payload" style="width: 500px; height: 200px;"></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Send Push" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Devices" asp-action="Index">Back to List</a>
</div>